services:
  alugue-car-build:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build"
    restart: "no"

  alugue-car-backend:
    image: node:18-alpine # Usando Node 18 para evitar problemas de compatibilidade
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npx ts-node src/server/index.ts"
    restart: always
    expose:
      - 3000
    environment:
      - DB_HOST=pgbouncer
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=OK4ut0MiCaoX
      - DB_NAME=alugue_car_v3
      - JWT_SECRET=UaXXghCUgW+dSU3rD8KXL5q9aNt2x8CPxJyWn8bOQjDLvAzCnwsGr4aM+2Y54kUZX/kP8qXGUIOb+IqGYDF9kA==
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alugue-car-backend.rule=Host(`api.alugue-car.okconnect.com.br`)"
      - "traefik.http.services.alugue-car-backend.loadbalancer.server.port=3000"

  alugue-car-frontend:
    image: nginx:alpine
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - alugue-car-backend
      - alugue-car-build
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alugue-car-frontend.rule=Host(`alugue-car.okconnect.com.br`)"
      - "traefik.http.services.alugue-car-frontend.loadbalancer.server.port=80"